### PR TITLE
Fix stream freezing when body ends unexpectedly

### LINKED ISSUE #67: Server hangs on unexpected end of body
Using `test_chunked_echo` test (it should also work with fixed-length bodies), with the following request:

```
POST / HTTP/1.1
content-type: text/plain
content-length: 11

aaaaabbbbb
```

### PR DESCRIPTION
**Pull request by tirr-c**
Fixes #67. Also fixes some state machine bugs found during testing. This might fix #63 also, I haven't tested it though.

This PR moves internal state to the end if the body ends unexpectedly.

### CODE REVIEW

**Comment by tirr-c** [comment]
I'm not quite sure if this approach is correct; @rylev would you take a look at this?

File: src/server.rs [hunk 1]
```diff
@@ -311,7 +335,18 @@ impl Read for Encoder {
...
+                    bytes_read += match inner_poll_result {
+                        Poll::Ready(Ok(n)) => n,
+                        Poll::Pending => {
+                            if bytes_read == 0 {
+                                return Poll::Pending;
+                            } else {
+                                break;
+                            }
+                        }
+                        e => return e,
```
Comment (yoshuawuyts) [inline src/server.rs]: Even though this is more typing, this should be easier to follow since all left-hand match arms then use fully qualified types, rather than a named catch-all argument as is the case now:

```suggestion
                        Poll::Ready(Err(e)) => return Poll::Ready(Err(e)),
```

File: src/server.rs [hunk 2]
```diff
@@ -237,8 +251,18 @@ impl Read for Encoder {
...
+                    let chunk_length = match inner_poll_result {
+                        Poll::Ready(Ok(n)) => n,
+                        Poll::Pending => {
+                            if bytes_read == 0 {
+                                return Poll::Pending;
+                            } else {
+                                break;
+                            }
+                        }
+                        e => return e,
```
Comment (yoshuawuyts) [inline src/server.rs]: Even though this is more typing, this should be easier to follow since all left-hand match arms then use fully qualified types, rather than a named catch-all argument as is the case now:

```suggestion
                        Poll::Ready(Err(e)) => return Poll::Ready(Err(e)),
```

File: src/server.rs [hunk 3]
```diff
@@ -198,9 +197,19 @@ impl Read for Encoder {
...
+                    let new_body_bytes_read = match inner_poll_result {
+                        Poll::Ready(Ok(n)) => n,
+                        Poll::Pending => {
+                            if bytes_read == 0 {
+                                return Poll::Pending;
+                            } else {
+                                break;
+                            }
+                        }
+                        e => return e,
```
Comment (yoshuawuyts) [inline src/server.rs]: Even though this is more typing, this should be easier to follow since all left-hand match arms then use fully qualified types, rather than a named catch-all argument as is the case now:

```suggestion
                        Poll::Ready(Err(e)) => return Poll::Ready(Err(e)),
```

File: src/client.rs [hunk 4]
```diff
@@ -241,7 +240,19 @@ impl Read for Encoder {
...
+            let n = match inner_poll_result {
+                Poll::Ready(Ok(n)) => n,
+                Poll::Pending => {
+                    if bytes_read == 0 {
+                        return Poll::Pending;
+                    } else {
+                        return Poll::Ready(Ok(bytes_read as usize));
+                    }
+                }
+                e => return e,
```
Comment (yoshuawuyts) [inline src/client.rs]: Even though this is more typing, this should be easier to follow since all left-hand match arms then use fully qualified types, rather than a named catch-all argument as is the case now:

```suggestion
                        Poll::Ready(Err(e)) => return Poll::Ready(Err(e)),
```

File: src/chunked.rs [hunk 5]
```diff
@@ -99,6 +99,10 @@ impl<R: Read + Unpin> ChunkedDecoder<R> {
                 read += n;
                 let new_state = if new_current == len {
                     State::ChunkEnd
+                } else if n == 0 {
+                    // Unexpected end
+                    // TODO: do something?
+                    State::Done
```
Comment (yoshuawuyts) [inline src/chunked.rs]: This seems like it should be an error. If no new data is passed we should indeed finish the stream, but because there's a mismatch between "expected length" and "actual length" it seems we should treat it as a protocol error.

Probably ignoring it for now though is fine; if the body ended prematurely any form of body parser will likely catch it (e.g. won't be valid json, csv, image, etc.).

So this seems good for now!
